[package]
name = "bluefile"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE.md"
readme = "README.md"
description = "Experimental Rust library for handling X-Midas Bluefiles."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
